#!/usr/bin/env python3
"""Normalize ship's driver-state stores into parley observer traces.

Reads ~/.workbench/driver-state/dsr_*/events.jsonl (or a dir from
argv[1]) and writes one trace per driver run to stdout. The abstraction,
matching protocols/driver-run.parley:

  run_imported       -> operator driver run.spec
  stream_dispatched  -> driver worker dispatch
  stream_attempt     -> worker driver attempt
  stream_pr_opened   -> worker repo pr.opened
  stream_merged      -> driver repo merge
  stream_skipped     -> driver operator skipped
  run_finished       -> driver operator finished

Every store observed so far is single-stream, so the stream label is
ignored; a multi-stream store would need per-stream traces.

Provenance filter: 235 of the 236 runs in the real ledger are fixture
runs (`manifest.generated_by: "test"`, phase `driver-cli-test`) that
leaked out of ship's test suite. Auditing those measures the fixtures,
not the work, so they are excluded by default. Pass --all to include
them; --only-test to look at the pollution itself.
"""

import json
import sys
from pathlib import Path

ARGS = [a for a in sys.argv[1:] if not a.startswith("--")]
FLAGS = {a for a in sys.argv[1:] if a.startswith("--")}
ROOT = Path(ARGS[0] if ARGS else Path.home() / ".workbench/driver-state")


def is_fixture(records: list) -> bool:
    """A run generated by a test manifest rather than by real work."""
    for record in records:
        if record["kind"] == "run_imported":
            manifest = record["body"].get("manifest", {})
            return manifest.get("generated_by") == "test"
    return False

EVENT = {
    "run_imported": "operator driver run.spec",
    "stream_dispatched": "driver worker dispatch",
    "stream_attempt": "worker driver attempt",
    "stream_pr_opened": "worker repo pr.opened",
    "stream_merged": "driver repo merge",
    "stream_skipped": "driver operator skipped",
    "run_finished": "driver operator finished",
}


def main() -> None:
    kept = skipped = 0
    for store in sorted(ROOT.glob("dsr_*/events.jsonl")):
        records = [json.loads(line) for line in store.read_text().splitlines()]
        records.sort(key=lambda r: r["time"])
        fixture = is_fixture(records)
        excluded = fixture if "--only-test" not in FLAGS else not fixture
        if excluded and "--all" not in FLAGS:
            skipped += 1
            continue
        kept += 1
        print(f"run {store.parent.name}")
        for record in records:
            print(EVENT.get(record["kind"], f"unmapped unmapped {record['kind']}"))
        print()
    print(
        f"{kept} runs emitted, {skipped} skipped by provenance filter",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
