#!/usr/bin/env python3
"""Generate protocols/gate-run.parley.

The real gate flow is a loop — park, respond (judgment or resolution),
re-verdict, decide again — and parley's algebra has no recursion yet, so
the protocol is this loop unrolled to DEPTH judged rounds (observed
maximum: four, roll-call PR 11). Regenerate with a bigger DEPTH if a run
ever legitimately loops deeper; the size of this file is the standing
argument for recursion in the algebra.

Each round:
  gate chooses: pass (pinned merge command) | park;
  a park goes to the judge, or to the operator once a grant ceiling is hit;
  the operator chooses how a park comes back: a judge judgment (then
  re-verdicts and the next round) or a named human resolution (terminal).
"""

DEPTH = 4

HEADER = """\
# GENERATED by observer/gen_gate_protocol.py — edit that, not this.
# One gate run, as actually practiced — reverse-engineered from
# ~/dev/gate/state/log.jsonl and refined until real history classifies
# cleanly (see observer/extract_gate.py for the record -> event mapping).
protocol gate-run
roles collector panel gate judge operator

collector -> gate: evidence.bundle
panel -> gate: verdicts
"""


def indent(depth: int) -> str:
    return "  " * depth


def emit(lines: list[str], depth: int, text: str) -> None:
    lines.append(indent(depth) + text)


def response(lines: list[str], d: int, round_: int) -> None:
    """After a park: the operator either sends the judge in, or resolves."""
    emit(lines, d, "choice operator observes collector panel gate judge {")
    emit(lines, d + 1, "judged {")
    emit(lines, d + 2, "judge -> gate: judgment")
    emit(lines, d + 2, "panel -> gate: re.verdicts")
    decision(lines, d + 2, round_ + 1)
    emit(lines, d + 1, "}")
    emit(lines, d + 1, "resolved {")
    emit(lines, d + 2, "operator -> gate: resolution")
    emit(lines, d + 1, "}")
    emit(lines, d, "}")


def park(lines: list[str], d: int, round_: int) -> None:
    emit(lines, d, "choice gate observes collector panel judge operator {")
    emit(lines, d + 1, "tojudge {")
    emit(lines, d + 2, "gate -> judge: escalation")
    if round_ <= DEPTH:
        response(lines, d + 2, round_)
    emit(lines, d + 1, "}")
    emit(lines, d + 1, "ceiling {")
    emit(lines, d + 2, "gate -> operator: escalation.ceiling")
    if round_ <= DEPTH:
        response(lines, d + 2, round_)
    emit(lines, d + 1, "}")
    emit(lines, d, "}")


def decision(lines: list[str], d: int, round_: int) -> None:
    """gate's pass-or-park decision for one round of verdicts."""
    emit(lines, d, "choice gate observes collector panel judge operator {")
    emit(lines, d + 1, "pass {")
    emit(lines, d + 2, "gate -> operator: merge.command")
    emit(lines, d + 1, "}")
    emit(lines, d + 1, "parked {")
    park(lines, d + 2, round_)
    emit(lines, d + 1, "}")
    emit(lines, d, "}")


def main() -> None:
    lines: list[str] = []
    decision(lines, 0, 1)
    print(HEADER + "\n".join(lines))


if __name__ == "__main__":
    main()
